# Form implementation generated from reading ui file 'loginForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class loginForm(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("QPushButton {\n"
"    background-color: #2196F3; /* 파란색 배경 */\n"
"    color: white; /* 흰색 글자 */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1976D2; /* 마우스를 올렸을 때 더 진한 파란색 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1565C0; /* 버튼을 눌렀을 때 더 어두운 파란색 */\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 160, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 240, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_basic_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_basic_login.setEnabled(True)
        self.btn_basic_login.setGeometry(QtCore.QRect(410, 310, 181, 101))
        self.btn_basic_login.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.btn_basic_login.setStyleSheet("QPushButton {\n"
"    background-color: #2196F3; /* 파란색 배경 */\n"
"    color: white; /* 흰색 글자 */\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    padding: 10px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1976D2; /* 마우스를 올렸을 때 더 진한 파란색 */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1565C0; /* 버튼을 눌렀을 때 더 어두운 파란색 */\n"
"}")
        self.btn_basic_login.setObjectName("btn_basic_login")
        self.btn_google_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_google_login.setGeometry(QtCore.QRect(410, 420, 181, 91))
        self.btn_google_login.setObjectName("btn_google_login")
        self.edit_id = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.edit_id.setGeometry(QtCore.QRect(220, 160, 371, 41))
        self.edit_id.setObjectName("edit_id")
        self.edit_pw = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.edit_pw.setGeometry(QtCore.QRect(220, 240, 371, 41))
        self.edit_pw.setObjectName("edit_pw")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "ID"))
        self.label_2.setText(_translate("MainWindow", "PW"))
        self.btn_basic_login.setText(_translate("MainWindow", "일반 로그인"))
        self.btn_google_login.setText(_translate("MainWindow", "구글 계정 로그인"))
