# Form implementation generated from reading ui file 'mainhomeForm.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(948, 887)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lbl_id = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_id.setGeometry(QtCore.QRect(190, -10, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.lbl_id.setFont(font)
        self.lbl_id.setStyleSheet("")
        self.lbl_id.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lbl_id.setObjectName("lbl_id")
        self.lbl_playerid = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_playerid.setGeometry(QtCore.QRect(250, -20, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lbl_playerid.setFont(font)
        self.lbl_playerid.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.lbl_playerid.setObjectName("lbl_playerid")
        self.btn_logout = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_logout.setGeometry(QtCore.QRect(310, 140, 101, 31))
        self.btn_logout.setAutoFillBackground(False)
        self.btn_logout.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.btn_logout.setObjectName("btn_logout")
        self.lstview_datastore = QtWidgets.QListView(parent=self.centralwidget)
        self.lstview_datastore.setGeometry(QtCore.QRect(630, 0, 291, 221))
        self.lstview_datastore.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.lstview_datastore.setObjectName("lstview_datastore")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, 240, 121, 41))
        self.pushButton.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.pushButton.setObjectName("pushButton")
        self.lbl_profile = ClickableLabel(parent=self.centralwidget)
        self.lbl_profile.setGeometry(QtCore.QRect(10, 0, 171, 161))
        self.lbl_profile.setMinimumSize(QtCore.QSize(171, 161))
        self.lbl_profile.setMaximumSize(QtCore.QSize(171, 161))
        self.lbl_profile.setAutoFillBackground(False)
        self.lbl_profile.setText("")
        self.lbl_profile.setPixmap(QtGui.QPixmap("0826/img/profile.png"))
        self.lbl_profile.setScaledContents(True)
        self.lbl_profile.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_profile.setObjectName("lbl_profile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 948, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_id.setText(_translate("MainWindow", "ID"))
        self.lbl_playerid.setText(_translate("MainWindow", "<player_id>"))
        self.btn_logout.setText(_translate("MainWindow", "로그아웃"))
        self.pushButton.setText(_translate("MainWindow", "데이터 추가"))

from ui.clickable_label import ClickableLabel